Django Backend Projects/foodmenu/food/urls.py
from django.urls import path
from food import views

app_name='food'
urlpatterns = [
    path('',views.IndexClassView.as_view(),name='home'),
    path('<int:pk>/',views.FoodDetail.as_view(),name='details'),
    path('add/',views.CreateItem.as_view(),name='create_item'), 
    path('update/<int:id>/',views.update_item,name='update_item'),
    path('remove/<int:id>/',views.remove_item,name='remove_item'),
    
]
 

Django Backend Projects/foodmenu/foodmenu/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')), 
    path('user/',include('user.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django Backend Projects/foodmenu/user/urls.py
from django.urls import path
from user import views as user_views
from django.contrib.auth import views as authentication_views


app_name='user'
urlpatterns = [
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='user/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='user/logout.html'),name='logout'),
    path('profile/',user_views.profile_page,name='profile'),
]

Django Backend Projects/foodmenu/food/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):

    def __str__(self):
        return self.item_name

    username=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name=models.CharField(max_length=100)
    item_desc=models.CharField(max_length=200)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=500,default="https://www.thefuzzyduck.co.uk/wp-content/uploads/2024/05/image-coming-soon-placeholder-01-660x660.png")

Django Backend Projects/foodmenu/user/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile_image/profile_img.jpg', upload_to='profile_image')
    location = models.CharField(max_length=500)

    def __str__(self):
        return self.user.username
    

Django Backend Projects/foodmenu/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=['item_name','item_desc','item_price','item_image']

Django Backend Projects/foodmenu/user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

                                                      

Django Backend Projects/foodmenu/food/views.py
from django.shortcuts import render,redirect
from .forms import ItemForm
from .models import Item
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.

# def home(request):
#     item_list=Item.objects.all()
#     context={
#         'item_list':item_list,
#     }
#     return render(request,'food/index.html',context)

class IndexClassView(ListView):
    model=Item
    template_name='food/index.html'
    context_object_name='item_list'

# Details
# def details(request,item_id):
#     item=Item.objects.get(pk=item_id)
#     context={
#         'item':item,
#     }
#     return render(request,'food/details.html',context)

class FoodDetail(DetailView):
    model=Item
    template_name='food/details.html'


# create_item
# def create_item(request):
#     form=ItemForm(request.POST or None)
#     if form.is_valid():
#         form.save()
#         return redirect('food:home')
#     return render(request,'food/item_form.html',{'form':form})

class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image'] 
    template_name = 'food/item_form.html' 
    success_url = '/food/'  

    def form_valid(self, form):
        form.instance.username = self.request.user
        return super().form_valid(form)

# update_item
def update_item(request,id):
    item=Item.objects.get(id=id)
    form=ItemForm(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:home')
    return render(request,'food/item_form.html',{'form':form,'item':item})

def remove_item(request, id):
    item = Item.objects.get(id=id)
    if request.method == 'POST':
        item.delete()  
        return redirect('food:home')  
    return render(request, 'food/remove.html', {'item': item})

Django Backend Projects/foodmenu/user/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save() 
            username=form.cleaned_data.get('username')
            messages.success(request,f'Welcome { username }, your account is created.')
            return redirect('user:login')
    else:
        form = RegisterForm()
    return render(request, 'user/register.html', {'form': form})


@login_required
def profile_page(request):
    return render(request,'user/profile.html')

Django Backend Projects/foodmenu/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FoodMenu</title>
    <!-- Custom Stylesheet -->
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <!-- Bootstrap Stylesheet -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url "food:home" %}">FoodMenu</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url "food:home" %}" class="nav-link">Menu Item</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'food:create_item' %}" class="nav-link">Add Item</a>
                    </li>
                </ul>
            </div>
            <nav class="navbar navbar-expand-lg bg-dark">
                <div class="container-fluid">
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a href="{% url 'user:profile' %}" class="nav-link" style="color: white;">Profile</a>
                            </li>
                            <li class="nav-item">
                                <form method="POST" action="{% url 'user:logout' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-link nav-link" style="color: white;">Logout</button>
                                </form>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a href="{% url 'user:register' %}" class="nav-link" style="color: white;">SignUp</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'user:login' %}" class="nav-link" style="color: white;">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            
                   
        </div>
    </nav>
    
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}

    <!-- Block for child templates to extend -->
    <div class="container mt-4">
        {% block body %}
        {% endblock %}
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-mQ93VfgNCzzIeypnYIH+KjP3G58DAXYZB6IhdxHiuMaEfBh+lHB7fIVwJyo9DSG9" crossorigin="anonymous"></script>
</body>
</html>

Django Backend Projects/foodmenu/food/templates/food/details.html
{% extends "food/base.html" %}

{% block body %}
<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="row">
        <div class="col-md-12 text-center">
            <img src="{{ object.item_image }}" class="card mb-3" style="width: 200px; height: auto; object-fit: cover;">
            <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h2>
            <h3>{{ object.item_price }}</h3>
        </div>
    </div>
</div>

{% endblock  %}

Django Backend Projects/foodmenu/food/templates/food/index.html
{% extends "food/base.html" %}

{% block body %}
    <div class="container mt-4">
        <div class="row">
            {% for item in item_list %}
                <div class="col-md-3 mb-4">  <!-- Use col-md-3 for four items per row on medium and larger screens -->
                    <div class="card h-100">
                        <img src="{{ item.item_image }}" height="150px" style="object-fit: cover;" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">{{ item.item_name }}</h5>
                            <p class="card-text">{{ item.item_desc }}</p>
                            <h6>₹{{ item.item_price }}</h6>
                            <h6>{{ item.username }}</h6>
                            <a href="{% url 'food:details' item.id %}" class="btn btn-success me-4 mb-3">Details</a>
                            <a href="{% url 'food:update_item' item.id %}" class="btn btn-warning mb-3">Update Item</a>
                            <a href="{% url 'food:remove_item' item.id %}" class="btn btn-danger w-100 mb-1">Remove Item</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

Django Backend Projects/foodmenu/food/templates/food/item_form.html
{% extends "food/base.html" %}
{% block body %}

<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6 col-lg-4">
            <div class="card shadow-lg border-0 rounded">
                <div class="card-header bg-info text-white text-center rounded-top">
                    <h3 class="card-title mb-0">Login</h3>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group mb-4">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                            {% if field.errors %}
                            <div class="text-danger small">{{ field.errors }}</div>
                            {% endif %}
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary w-100">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

Django Backend Projects/foodmenu/food/templates/food/remove.html
{% extends "food/base.html" %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        <h2>Are you sure want to remove {{ item.item_name }}</h2>
        <button type="submit" class="btn btn-danger">Confrim</button>
    </form>
{% endblock  %}

Django Backend Projects/foodmenu/user/templates/user/login.html
{% extends "food/base.html" %}
{% block body %}

<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6 col-lg-4">
            <div class="card shadow-lg border-0 rounded">
                <div class="card-header bg-info text-white text-center rounded-top">
                    <h3 class="card-title mb-0">Login</h3>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group mb-4">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                            {% if field.errors %}
                            <div class="text-danger small">{{ field.errors }}</div>
                            {% endif %}
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary w-100">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

Django Backend Projects/foodmenu/user/templates/user/logout.html
{% block body %}
    <p>You have successfully logged out. Click <a href="{% url 'user:login' %}">here</a> to login again.</p>
{% endblock %}

Django Backend Projects/foodmenu/user/templates/user/profile.html
<img class="img-fluid rounded" style="height: 180px; width: 150px; border: 2px solid black; object-fit: cover;" src="{{ user.profile.image.url }}">
<h2>{{ user.username }}</h2>

Django Backend Projects/foodmenu/user/templates/user/register.html
{% extends "food/base.html" %}
{% block body %}

<div class="container">
    <div class="row justify-content-center mt-6">
        <div class="col-md-6 col-lg-4">
            <div class="card shadow-lg border-0 rounded">
                <div class="card-header bg-info text-white text-center rounded-top">
                    <h3 class="card-title mb-0">Register User</h3>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group mb-4">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                            {% if field.errors %}
                            <div class="text-danger small">{{ field.errors }}</div>
                            {% endif %}
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary w-100">SignUp</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}